version: 2.1
jobs:
  build:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - metadeploy-py-{{ checksum "requirements/prod.txt" }}-{{ checksum
              "requirements/dev.txt" }}
      - restore_cache:
          keys:
            - metadeploy-npm-{{ checksum "yarn.lock" }}
            - metadeploy-npm-
      - run:
          name: Install Node & Yarn
          command: ./bin/unpack-node
      - run:
          name: Set $PATH
          command: |
            echo 'export PATH=~/metadeploy/node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=~/metadeploy/node/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install pip-tools
            make dev-install
      - run:
          name: Compile Front-End Assets
          command: yarn prod
      - persist_to_workspace:
          root: .
          paths:
            - ./dist
            - ./venv
            - ./node_modules
            - ./node
      - save_cache:
          key:
            metadeploy-py-{{ checksum "requirements/prod.txt" }}-{{ checksum
            "requirements/dev.txt" }}
          paths:
            - ./venv
      - save_cache:
          key: metadeploy-npm-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  lint:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set $PATH
          command: |
            echo 'export PATH=~/metadeploy/node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=~/metadeploy/node/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            yarn lint:nofix

  test-client:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set $PATH
          command: |
            echo 'export PATH=~/metadeploy/node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=~/metadeploy/node/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Test JS
          command: yarn test:js:coverage
      - store_artifacts:
          path: coverage
          destination: js-reports
      - store_test_results:
          path: coverage
      - persist_to_workspace:
          root: .
          paths:
            - coverage

  test-python:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.8
        environment:
          SFDX_CLIENT_CALLBACK_URL: circle_test
          SFDX_CLIENT_ID: circle_test
          SFDX_CLIENT_SECRET: circle_test
          DATABASE_URL: postgres://ubuntu:circle_test@localhost:5432/circle_test
          DB_ENCRYPTION_KEY: s38Tpa-rzNJsDwmn_bNuUK4T1zaNG9j1J9u1Yrk9P9c=
          DJANGO_DEBUG: False
          DJANGO_HASHID_SALT: test_hash_id
          DJANGO_SECRET_KEY: test_secret_key
          DJANGO_SETTINGS_MODULE: config.settings.test
          GITHUB_TOKEN: circle_test
          SECURE_SSL_REDIRECT: False
      - image: circleci/redis:6
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circle_test
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Dockerize
          command:
            wget
            https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            && sudo tar -C /usr/local/bin -xzvf
            dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm
            dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run Database Migrations
          command: |
            . venv/bin/activate
            python ./manage.py migrate --no-input
      - run:
          name: Test Python
          command: |
            . venv/bin/activate
            pytest --junitxml=pycov/pytest-junit.xml
      - store_artifacts:
          path: htmlcov
          destination: py-reports
      - store_test_results:
          path: pycov
      - persist_to_workspace:
          root: .
          paths:
            - .coverage

  report-test-coverage:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.8
    environment:
      COVERALLS_PARALLEL: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set $PATH
          command: |
            echo 'export PATH=~/metadeploy/node_modules/.bin:$PATH' >> $BASH_ENV
            echo 'export PATH=~/metadeploy/node/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Report Test Coverage
          command: |
            export COVERALLS_SERVICE_NUMBER=$CIRCLE_BUILD_NUM
            export COVERALLS_SERVICE_JOB_ID=$CIRCLE_WORKFLOW_ID
            . venv/bin/activate
            yarn test:py:report-coverage
            yarn test:js:report-coverage
            curl -k "https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}" -d "payload[build_num]=${CIRCLE_BUILD_NUM}&payload[status]=done"
      - run:
          name: Check Test Coverage
          command: |
            . venv/bin/activate
            yarn test:py:check-coverage
            yarn test:js:check-coverage

  build-docs:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Documentation
          command: |
            . venv/bin/activate
            cd docs
            make html
  deploy-storybook:
    working_directory: ~/metadeploy
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - 'c1:84:57:29:98:26:96:91:21:f4:bf:93:b4:7a:5d:e8'
      - run:
          name: Deploy Storybook
          command: |
            if [ -n "${DEPLOY_STORYBOOK}" ]; then
              yarn deploy-storybook --ci
            fi

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test-client:
          requires:
            - build
      - test-python:
          requires:
            - build
      - build-docs:
          requires:
            - build
      - deploy-storybook:
          requires:
            - build
          filters:
            branches:
              only: main
      - report-test-coverage:
          requires:
            - test-client
            - test-python
