name: Test
on:
  push:
  pull_request:
    types: [reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: sfdc-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-docker-compose
        with:
          # By writing to the cache here subsequent jobs will get the updated
          # image when they use setup-docker-compose
          cache-to: type=gha,mode=max

  lint:
    name: Lint
    needs: [build]
    runs-on: sfdc-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-docker-compose
      - name: Lint
        run: docker-compose run --no-deps web yarn lint:nofix

  frontend:
    name: Frontend
    needs: [build]
    runs-on: sfdc-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-docker-compose
      - name: Test frontend
        run: docker-compose run --no-deps web yarn test:js:coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: |
            coverage

  backend:
    name: Backend
    needs: [build]
    runs-on: sfdc-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: ./.github/setup-docker-compose
      - name: Copy index.html for Django templates
        run: |
          mkdir -p dist
          docker cp $(docker create ${{ steps.setup.outputs.tag }}):/app/dist/prod/index.html ./dist/
      - name: Test backend
        # prettier-ignore
        run: >
          docker-compose run
          -e DB_ENCRYPTION_KEY=MMkDMBfYL0Xoz3Xu1ENs3AkdCZdJoks5PNlUBkK7KDc=
          -e DJANGO_DEBUG=false
          -e SECURE_SSL_REDIRECT=false
          -e GITHUB_TOKEN="sample token"
          -e SFDX_CLIENT_SECRET="sample secret"
          -e SFDX_CLIENT_CALLBACK_URL="sample callback"
          -e SFDX_CLIENT_ID="sample id"
          -e SFDX_HUB_KEY="sample key"
          web yarn test:py
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: |
            .coverage
            coverage.xml

  coverage:
    name: Coverage
    needs: [frontend, backend]
    runs-on: sfdc-ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-docker-compose
      - name: Download frontend coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-coverage
          path: coverage
      - name: Download backend coverage artifacts
        uses: actions/download-artifact@v3
        with:
          name: backend-coverage
      - name: Check coverage
        run: |
          docker-compose run --no-deps web yarn test:js:check-coverage
          docker-compose run --no-deps web yarn test:py:check-coverage
